#nginx:
  #image: jwilder/nginx-proxy:latest
  #  build: nginx/
  #  ports: 
  #    - "80:80"
  #  volumes:
  #    - /var/run/docker.sock:/tmp/docker.sock

bbb:
  build: .
  ports:
   - "80:80"
  expose:
  #- "80"
  - "9123:9123"
  - "1935:1935"  
  environment:
      SERVER_NAME: meet.example.com
      MOBILE_SALT: 03b07
      VIRTUAL_HOST: meet.example.com
      BBB_INSTALL_DEMOS: "yes"
#  privileged: true
